name: zine_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  video_player: ^2.6.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  lottie: 3.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Assets should be indented under flutter:
  assets:
    - assets/launcher.png
    - assets/animations/

flutter_icons:
  android: true  # Enable for Android
  ios: true      # Enable for iOS
  image_path: "assets/launcher.png"